version: '3'

services:
  website:
    build: .
    ports:
    - 4000:4000
    volumes:
    - .:/src
    environment:
    - JEKYLL_GITHUB_TOKEN=${JEKYLL_GITHUB_TOKEN}
    command: bundle exec jekyll serve --host 0.0.0.0 --incremental
